language: node_js
node_js:
  - "10.15.3"
before_install:
  - npm i -g npm@6.4.1
install:
  - npm install
script:
  - gulp indigo-sass
  - gulp indigo-react
  # - npm run test
# Send coverage data to Coveralls
# after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"
